@url = https://8080-lucaspcode-primeiraapi2-xqhvik1rh5a.ws-us121.gitpod.io/alunos

POST {{url}}
Content-Type: application/json

{
    "nome": "Paula",
    "idade": 36
}

###
GET {{url}}

###
PUT {{url}}/4
Content-Type: application/json

{
    "nome": "Jurandir",
    "idade": 89
}

###
DELETE {{url}}/3

###
GET {{url}}/3