@url = https://8080-lucaspcode-primeiraapi2-xqhvik1rh5a.ws-us121.gitpod.io/alunos

POST {{url}}
Content-Type: application/json

{
    "id": 2,
    "nome": "Ana",
    "idade": 19
}

###
GET {{url}}

###
PUT {{url}}/2
Content-Type: application/json

{
    "nome": "Ademar"
}

###
DELETE {{url}}/2

###
GET {{url}}/2