@url = https://8080-lucaspcode-primeiraapi2-xqhvik1rh5a.ws-us121.gitpod.io/alunos

POST {{url}}
Content-Type: application/json

{
    "nome": "Carlos",
    "idade": 21
}

###
GET {{url}}

###
PUT {{url}}/4
Content-Type: application/json

{
    "nome": "Ademar",
    "idade": 40
}

###
DELETE {{url}}/3

###
GET {{url}}/3